baseURL = 'https://hansarick.com'
languageCode = 'en-us'
title = 'The Hansaricks'

# Using docs directory for GitHub, since it likes either root or docs.
# turning off the publish docs check
publishDir = "docs"

contentDir = "content"


[params]
    # Enable Lunr.js offline search
    offlineSearch = true

# Comment out if you don't want the "print entire section" link enabled.
[outputs]
  section = ["HTML", "print", "RSS"]

[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
